# /etc/nginx/conf.d/nycynapse-rate-limit.conf
limit_req_zone $binary_remote_addr zone=nycynapse_per_ip:1m rate=120r/m;
limit_req_zone $binary_remote_addr zone=nycynapse_ask:1m rate=6r/m;
limit_conn_zone $binary_remote_addr zone=nycynapse_conn_per_ip:1m;
